### PR TITLE
Content: Article for Dashboard 0.8.0 Release

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

- We've just released `0.8.0` version for Node-RED Dashboard 2.0, this article details some of the bigger changes
- Also reminds people that we've switched over to `@flowfuse` as a repo now

Closes https://github.com/FlowFuse/website/issues/1343

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
Well written as always. Thanks

**Comment by ZJvandeWeg** [comment]
@joepavitt can you schedule this post for social media?

**Comment by joepavitt** [comment]
Last time I checked, I don't have hubspot access, so I can't

**Comment by joepavitt** [comment]
Just double checked, still no access, not been able to since domain switch.



My Google Account is `joepavitt@flowfuse.com`

**Pull request merged**
