### PR TITLE
v2.12 Release Post (with Freemium Announcement)

### PR DESCRIPTION
**Pull request by gstout52**
Freemium release post draft

## Description

Draft of the freemium release announcement

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [] Suitable unit/system level tests have been added and they pass
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by joepavitt** [comment]
This branch was very outdated, so just merged it with `main` to get the latest version of the website in

**Comment by joepavitt** [comment]
Just a heads up for the next article you write, this will be a useful resource: https://flowfuse.com/handbook/customer/marketing/blog/#blog

**Comment by gstout52** [comment]
> This branch was very outdated, so just merged it with `main` to get the latest version of the website in

Thanks @joepavitt ! Can you tell me which step I got wrong? I had created a new branch and had it set to commit to Main. Maybe because my branch was based on an already outdated branch?

**Comment by joepavitt** [comment]
The branching part was all good, it was more how to write the Markdown, and the `frontmatter` that goes at the start of the `md` file to define the relevant properties for the article

I have the changes locally, but got sidetracked with the UI work for team type selection, happy to jup on a call later and cover it

**Comment by gstout52** [comment]
> The branching part was all good, it was more how to write the Markdown, and the `frontmatter` that goes at the start of the `md` file to define the relevant properties for the article
> 
> I have the changes locally, but got sidetracked with the UI work for team type selection, happy to jup on a call later and cover it

Gotcha. We can just talk during our 1-1, no need to distract from Release Eve just for my education :)

**Comment by joepavitt** [comment]
Everything in place, this should now be good to go tomorrow (FYI @knolleary and @gstout52)

**Pull request merged**
