### PR TITLE
Adds a 'deploy to flowfuse' button for each blueprint

### PR DESCRIPTION
**Pull request by cstns**
## Description

Adds a 'deploy to flowfuse' button for each blueprint

## Related Issue(s)

depends on https://github.com/FlowFuse/blueprint-library/pull/58
closes https://github.com/FlowFuse/website/issues/2285

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@cstns https://deploy-preview-2315--flowforge-website.netlify.app/blueprints/ 404s for me, is that expected?

**Comment by cstns** [comment]
> @cstns https://deploy-preview-2315--flowforge-website.netlify.app/blueprints/ 404s for me, is that expected?

I'm not quite sure why it's happening. Locally I'd get this 404 if the blueprints repository isn't available or the blueprints weren't copied over when the website gets built

**Comment by cstns** [comment]
The blueprints command ran successfully when the deployment ran
image

Not sure what's happening

@joepavitt, should we move forward or investigate?

**Comment by ZJvandeWeg** [comment]
If it works locally, we can move forward and revert if it's broken on prod too.

**Comment by cstns** [comment]
Ok! I'll merge it and keep an eye on prod

**Comment by cstns** [comment]
looking good on prod

**Pull request merged**
