### PR TITLE
Workshop: Dashboard Crash Course

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Draft detail for the propose Dashboard workshop we'll host on July 2nd.

### Outstanding Tasks

```[tasklist]
- [ ] https://github.com/FlowFuse/website/issues/2222
- [x] Setup Hubspot form to capture registrations
- [x] Ensure restream setup is documented, and works, ahead of the event
```

## Related Issue(s)

Closes: https://github.com/FlowFuse/customer/issues/218

### CODE REVIEW

**Comment by joepavitt** [comment]
FYI @gdziuba

**Comment by joepavitt** [comment]
@gdziuba could we have the Hubspot side of this ready for today? I want to post about our [new article](https://flowfuse.com/blog/2024/06/dashboard-multi-tenancy/) into the Node-RED Discourse, and this would be a nice CTA.

May even modify the article itself to add this as a CTA at the bottom.

**Comment by gdziuba** [comment]
@joepavitt 

[Invite Guests Link](https://app.restream.io/new-event-invitation/elB3OVdQdpdkVMg0DkMPugmao8D19oA/email)

[Instructions for Guests](https://support.restream.io/en/articles/5387435-i-want-to-add-my-channels-as-a-guest-to-a-scheduled-event)

**Comment by joepavitt** [comment]
> @joepavitt
> [Invite Guests Link](https://app.restream.io/new-event-invitation/elB3OVdQdpdkVMg0DkMPugmao8D19oA/email)
> 
> [Instructions for Guests](https://support.restream.io/en/articles/5387435-i-want-to-add-my-channels-as-a-guest-to-a-scheduled-event)

Is this all included automatically in the e-mail users will get when registering?

**Comment by joepavitt** [comment]
Also, the Instructions for Guests seems quite hands-on? Isn't it just a YouTube URL that they get sent?

**Review by Hasmin-AC — APPROVED** [review]

**Comment by gdziuba** [comment]
Documentation that needs to go to Handbook:

1. Create an Event in Restream.io
    - Pick the destination of where you want to stream to
2. Create Webpage
3. Leverage the Workshop workflow in hubspot
    - Create a new form
    - Create a new list
    - Create an email
    - Create an ics calendar invite
    - link ics calendar invite
    - load ics calendar invite into hubspot so it can be linked

**Comment by gdziuba** [comment]
> > @joepavitt
> > [Invite Guests Link](https://app.restream.io/new-event-invitation/elB3OVdQdpdkVMg0DkMPugmao8D19oA/email)
> > [Instructions for Guests](https://support.restream.io/en/articles/5387435-i-want-to-add-my-channels-as-a-guest-to-a-scheduled-event)
> 
> Is this all included automatically in the e-mail users will get when registering?

This info is for you.  This is how you will join.  I will host.

The guest email will get a calendar invite for them to join a youtube event.  

This is the link: https://www.youtube.com/watch?v=uxBz3qs7qZk

**Pull request merged**
