### PR TITLE
Add sign up to navbar

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

We replaced the sign-up button with the 'talk to sales' option. Now, we're adding it as a third button to ensure all options are visible on every page. I restyled the navbar to accommodate the third option and improve color contrast.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-FlowForge** [comment]
We still need to make more changes to the navbar, but will open a new issue/PR for that.

**Comment by Yndira-FlowForge** [comment]
Hi @ZJvandeWeg is this one ok to be merged?

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge I don't think this is the right direction:
1. The styling is off, it's not obvious anymore that this is a nav bar. Why have you changed the styling?
2. The discussion concluded with a carret like below (better styling etc, but as example)

Screenshot 2024-01-12 at 15 24 06

**Comment by Yndira-FlowForge** [comment]
> The styling is off, it's not obvious anymore that this is a nav bar. Why have you changed the styling?

I examined the navbars on the reference websites featured in our handbook:
Screenshot 2024-01-12 at 15 39 13

Screenshot 2024-01-12 at 15 39 01

Screenshot 2024-01-12 at 15 38 31

Screenshot 2024-01-12 at 15 38 17

I observed that ours stands out too much—the font is too large, and the red against that background didn't pass the contrast checker for fonts below 18pt.
Screenshot 2024-01-12 at 15 52 50

It's currently like this:
Screenshot 2024-01-12 at 15 47 10

And I'm proposing this:
Screenshot 2024-01-12 at 15 37 54

> The discussion concluded with a carret like below (better styling etc, but as example)

This was one option, and I mentioned that I would explore the available choices to determine which might be the best fit for us. After researching, I concluded that having all options visible would be the best approach, reducing the number of clicks for users to reach their desired destination.

**Comment by ZJvandeWeg** [comment]
@Yndira-FlowForge That works indeed

**Comment by Yndira-FlowForge** [comment]
I've restyled the webinar banner, it has more contrast against the navbar and I think it works well with dark and light pages.

Screenshot 2024-01-15 at 10 13 07

Screenshot 2024-01-15 at 10 13 18

**Pull request merged**
