### PR TITLE
Install edge plugin and implement a/b test

### PR DESCRIPTION
**Pull request by Yndira-E**
## Description

We'd like to A/B test the `talk to us` button label on the main nav, using `contact us` as the alternative.

This PR reintroduces the edge plugin and add the necessary feature flag for the A/B test.

## Related Issue(s)

https://github.com/FlowFuse/customer/issues/225

And reverted the changes from this PR https://github.com/FlowFuse/website/pull/1953

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by joepavitt** [comment]
Things worth flagging:

- build time increase
- Netlify ££ cost

The cost given website traffic _should_ be negligible (~$10/month), the build time increases hopefully have been covered with other improvements in hte website build process recently, so shouldn't have too much of an impact

**Comment by joepavitt** [comment]
The other advantage here is that reintroducing the edge plugin, _should_ fix the posthog disconnect currently happening between the website and app too.

**Review by joepavitt — APPROVED** [review]

**Comment by joepavitt** [comment]
Tested locally, verified in PH too

**Comment by Yndira-E** [comment]
And for the record, [this is the experiment](https://eu.posthog.com/project/2209/experiments/15058).

**Pull request merged**
