### PR TITLE
feature table reorg

### PR DESCRIPTION
**Pull request by zackwasli**
## Description

We should re-organize our feature table to match our current messaging framework, which is:

Manage
Scale
Secure
Collaborate

Additionally, we need to add a box for "BAA for HIPAA compliance" under Secure, but only checked for Enterprise.

Please note, current commit does not contain necessary changes yet. 

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@Yndira-E LMK WDYT.

**Comment by Yndira-E** [comment]
Looks good! but that only covers

> we need to add a box for "BAA for HIPAA compliance" under Secure, but only checked for Enterprise.

For the re-organizing part, would this make sense?

### Manage
- Node-RED Hosting
- Hosted Instances
- Edge Devices
- Instance Monitoring
- Persistent files
- Persistent Context
- Custom Hostnames

### Scale
- Edge Development
- Device Management
- Device Group Management
- MQTT Broker
- High Availability
- DevOps Pipelines

### Secure
- Audit Log
- Role-Based Access Control
- Endpoint Security
- Two-factor authentication
- Certified Nodes
- Single Sign-On (SSO)

### Collaborate
- Team members
- Access to Blueprints
- Node-RED Dashboard
- Personalised Multi-user Dashboards
- Seamless Data Stream

**Comment by zackwasli** [comment]
That looks good, maybe Seamless data stream should go into scale? It's one of the most sought after features, so I want to be careful not to bury it. But I understand that we don't want to take too much away from the Collaborate column, so I'm not sure

**Comment by Yndira-E** [comment]
Done! I’ve already reorganized the features table, including the feature added by ZJ.

**Pull request merged**
