### PR TITLE
community: Add a Node-RED consultants page

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
This is a bare-bones iteration of a list of Node-RED consultants. While this list is by no means exhaustive or even close to being, I wanted to record these changes to start collaboration on this list.

The goal is to list known Node-RED consultants for the community to go to. FlowForge doesn't offer professional services, but we can help others find them.

This change is missing a navigation route, and about 15 more consultants before it's ready for publishing. As well as a design overhaul.

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@joepavitt If you have time, can you look at designing the page? I've copied the idea from the team page, but think the team page needs headshots and this page logos. WDYT?

**Comment by joepavitt** [comment]
Agreed - will add to my todo list to create a design that can be reflected across both instances.

**Comment by kazuhitoyokoi** [comment]
Hello! Recently, admin members (@joeartsea, @1ft-seabass, @taijihagino, and @kazuhitoyokoi) of Node-RED Japan User Group established the organization. Can we join the following consultant list? Are there rules to add it?

```
{
    "name": "End User Computing Association",
    "website": "https://www.euca.in",
    "country": "JP",
    "email": "contact@euca.in",
    "linkedin": "https://www.linkedin.com/company/end-user-computing-association/",
    "expertise": [
        "prototyping",
        "node development",
        "seminar",
        "Industry 4.0"
    ]
}
```

I believe that we have the most knowledge and experience about Node-RED at least in Japan. I hope that you already know about us from Node-RED Con and other activities but we can explain about ourselves if needed.

**Comment by ZJvandeWeg** [comment]
Will do!Op 22 okt. 2022 00:44 schreef Kazuhito Yokoi ***@***.***>:
Hello! Recently, admin members ***@***.***, @1ft-seabass, @taijihagino, and @kazuhitoyokoi) of Node-RED Japan User Group established the organization. Can we join the following consultant list? Are there rules to add it?
{
    "name": "End User Computing Association",
    "website": "https://www.euca.in",
    "country": "JP",
    "email": ***@***.***",
    "linkedin": "https://www.linkedin.com/company/end-user-computing-association/",
    "expertise": [
        "prototyping",
        "node development",
        "seminar",
        "Industry 4.0"
    ]
}

I believe that we have the most knowledge and experience about Node-RED at least in Japan. I hope that you already know about us from Node-RED Con and other activities but we can explain about ourselves if needed.

**Comment by kazuhitoyokoi** [comment]
@ZJvandeWeg Great! Thank you. Let's collaborate in Node-RED community. :)

**Comment by joepavitt** [comment]
reasonable to ask for a photo/logo for each of these entries? Gives us more scope in the design to make it a little prettier

**Pull request closed without merging**
