### PR TITLE
handbook: Add our legal agreement

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
It's now linked from a Google Doc, but when there's no changes it's better to just capture this doc in the handbook. Also adds a form to request the docx through an email.

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by ZJvandeWeg** [comment]
@Yndira-E I think the form is just broken right now on the page, and I don't quite understand why. Can you poke at this for a couple of minutes?

**Comment by Yndira-E** [comment]
On it @ZJvandeWeg

**Comment by Yndira-E** [comment]
It works on .njk files, if you change the extension of this md to njk it'll work. You could just copy/paste the script into the md or we could add a configuration to eleventy.js to make all md process nunjucks syntax, but I'm not sure that's what we want here.

**Comment by ZJvandeWeg** [comment]
Done, thanks @Yndira-E. Appreciate your time and debugging

**Comment by Yndira-E** [comment]
What I meant was that the form would appear if you change the extension, but you lose the md formatting if you do. The quickest fix would be to add the script directly into the md, [like in our docs](https://github.com/FlowFuse/flowfuse/blob/main/docs/install/introduction.md?plain=1).

**Pull request merged**
