### PR TITLE
FAQs

### PR DESCRIPTION
**Pull request by joepavitt**
Further work on #254 - to be merged once #271 is in.

For the list of questions and answers included, see [src/_data/faqs.json](https://github.com/flowforge/website/blob/faqs/src/_data/faqs.json)

### CODE REVIEW

**Comment by joepavitt** [comment]
The questins i've put in so far have come from the most common issues/rickets raised that I've seen, along with conversations/comments I've seen in the likes of Reddit and #flowforge in Node RED Slack

**Comment by ZJvandeWeg** [comment]
@joepavitt Is it ok to take the plumbing of this PR and add it to our Node-RED page to add a FAQ there? Content is in: https://docs.google.com/document/d/1vZ3kE72g5ACP6RTmXwjta0afgzYb6VDyGyVPOEw6VFw/edit#heading=h.1xz8sv7cpdq9

**Comment by joepavitt** [comment]
Absolutely - it's mostly why I've left this here, because I knew it'd come in handy at some point!

**Comment by joepavitt** [comment]
Closing this is not going to be merging anytime soon

**Pull request closed without merging**
