### PR TITLE
Handbook: Update Personas

### PR DESCRIPTION
**Pull request by gdziuba**
## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by gdziuba** [comment]
@Yndira-E Can we get a new image for Steve and Sarah?

**Comment by gdziuba** [comment]
@joepavitt Can you take a look at this and see why the tests aren't passing?

**Comment by joepavitt** [comment]
I don't work Mondsys. @knolleary can look today, otherwise, I can tomorrow

**Comment by gdziuba** [comment]
@joepavitt Sorry forgot, but It can wait.  Nothing that needs to go out today.

**Comment by Yndira-E** [comment]
@gdziuba done!

**Comment by joepavitt** [comment]
Problem was fixed in https://github.com/FlowFuse/website/pull/2378 - will rebase this branch so that it passes

**Comment by ZJvandeWeg** [comment]
I feel like we have quite a few persona's now, @gdziuba @joepavitt Can you remove a few we shouldn't focus on?

**Comment by joepavitt** [comment]
Agree @gdziuba

**Pull request merged**
