### PR TITLE
Indicate true pricing on the website

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

- Changed the main toggle to switch between monthly and annually.
- Removed the starter plan from the annual option.
- Added sliders to the team and enterprise plans to calculate prices with discounts applied based on volume and billing frequency.
- Updated the "Contact Us" link to scroll down to the form.

## Related Issue(s)

closes [#1662](https://github.com/FlowFuse/website/issues/1662)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Review by zackwasli — APPROVED** [review]

**Comment by knolleary** [comment]
One piece of feedback, I don't know if this is intentional. If I select the annual option, the pricing is still labeled as per-month - it doesn't tell me what the annual cost is:

image

**Comment by Yndira-FlowForge** [comment]
Hi @knolleary, thanks for the feedback 🙂

It is intentional, aimed at making it easier to compare prices.

Initially, I displayed monthly prices in the monthly section and annual prices in the annual section, but it seemed a bit confusing, especially with the high annual figure. It's not common to see such large numbers on pricing pages.

Upon further review of other pricing pages for reference:

[Asana Pricing](https://asana.com/pricing)
[Dropbox Business Plans](https://www.dropbox.com/business/plans-comparison?billing=yearly)
[Canny Pricing](https://canny.io/pricing)
[Grammarly Plans](https://www.grammarly.com/plans)

I noticed they all show monthly prices in their yearly and monthly billing options. So, I thought it would be beneficial to provide a consistent basis for comparison.

**Comment by knolleary** [comment]
@Yndira-FlowForge thanks for the detailed reply. Makes sense to me - especially if this appears to be a standard practice.

**Comment by Yndira-FlowForge** [comment]
@knolleary I meant to add you as a reviewer yesterday, and now I see I didn't. Would you mind checking the code as well? It's working fine, @zackwasli confirmed the numbers were correct, but I'd appreciate a double-check on the script.

**Pull request merged**
