### PR TITLE
Dashboard ebook and thank you pages

### PR DESCRIPTION
**Pull request by Yndira-E**
## Description

Created the `eBook` and `thank you` pages using the templates created for these pages

## Related Issue(s)

#2220

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-E** [comment]
Hi @Hasmin-AC, the pages are completed. The only thing remaining is the dashboard images you mentioned in the issue. Which images would you like?

I recall you didn't prefer the one we used on the Dashboard landing page mockup, and using the same image across all three pages might seem repetitive. Could you please share your thoughts on what you had in mind?

**Comment by Yndira-E** [comment]
We could merge as is and add the images as an iteration

**Comment by ZJvandeWeg** [comment]
As Hasmin is OOO today, I'll merge as is, and you can schedule the next iteration next week @Yndira-E ?

**Comment by Yndira-E** [comment]
Yes, as soon as Hasmin shares which images she had in mind, I'll get on it.

**Pull request merged**
