### PR TITLE
New pricing for FF self hosted

### PR DESCRIPTION
**Pull request by MarianRaphael**
## Description

Pricing update for Self hosted FF-Instances:

- $25 per instance (no matter if it's a device or a hosted instance)

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowforge/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by zackwasli** [comment]
What is the reasoning behind just changing the self-hosted price?

**Comment by ZJvandeWeg** [comment]
@zackwasli thats the price we can change today without effecting current customers

**Comment by zackwasli** [comment]
@MarianRaphael ZJ and I just made a plan for me to change the pricing for existing customers in Stripe and provide coupons in the first week of January. Let's please proceed with the pricing changes, but have the same $25 per instance per month for both Cloud and Self-Hosted

**Comment by MarianRaphael** [comment]
Okay, no problem from my side; we can take care to update the product price tags. However, please inform the customers in the tier about the price change, even if they receive a coupon for the first month.

**Comment by MarianRaphael** [comment]
> have the same $25 per instance per month for both Cloud and Self-Hosted

PR is updated

**Pull request merged**
