### PR TITLE
Update hero.json

### PR DESCRIPTION
**Pull request by gstout52**
Updated tagline and subtitle on homepage

## Description

This change updates the tagline to emphasize manufacturing use and that FlowFuse is a comprehensive platform.

## Related Issue(s)

#2796 

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [] Suitable unit/system level tests have been added and they pass
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by gstout52** [comment]
@Hasmin-AC , @Yndira-E

**Comment by ZJvandeWeg** [comment]
The thing I'm missing in the PR is the why. Why this line, and why is it better. Can you elleborate?

**Comment by gstout52** [comment]
> The thing I'm missing in the PR is the why. Why this line, and why is it better. Can you elleborate?

Yes. The new headline (1) emphasizes manufacturing as our primary application, in line with our ICP and (2) focuses on our offering a comprehensive IT/OT solution (hint: not just managing Node-RED).

The new subheading surfaces concepts from our wheel further down the page - manage, secure, scale, collaborate - and better highlights what FlowFuse does: 'supercharges manufacturing operations'.

We can merge this, then keep an eye on homepage engagement, sales hand-raises, and trial signups, and compare before/after as A/B versions.

**Comment by Hasmin-AC** [comment]
Changing the descriptor of what we offer (from industrial data platform to IT/OT platform) is a significant change we probably need to think about more wholistically. Just my 2 cents :)

**Comment by Yndira-E** [comment]
I think the tagline might need a bit more thought, and if we could make it shorter in the process, that would be great. Is IT/OT integration all that FF/NR have to offer in manufacturing? Or is it part of something bigger? Or is this the umbrella term that would include everything they enable?

As for the subtitle, I believe @Hasmin-AC had it on her to-do list since the wheel hadn’t been added to the page when it was created. But now that it’s there, it feels a bit repetitive.

**Comment by ZJvandeWeg** [comment]
> a comprehensive IT/OT solution

I feel like the solution connects the shopfloor to the rest of the business. IT/OT are two teams that need to converge, but it's highly political? Not sure if this is the right phrasing.

**Comment by joepavitt** [comment]
> Changing the descriptor of what we offer (from industrial data platform to IT/OT platform) is a significant change we probably need to think about more wholistically. Just my 2 cents :)

I'm not convinced it's that drastic a change. We also should be iterating faster than we are, and Greg has shown, our home page to CTA conversion is poor, we need drastic changes.

**Comment by ZJvandeWeg** [comment]
Joe and Greg, you can merge as is if you report back in two weeks.

**Comment by Hasmin-AC** [comment]
To be clear, I'm not opposed at all to changing the tagline. And think we should wordsmith it so that it resonates better and we get more engagement. 

I would only be careful that we don't miss the essense of what we are all about when making changes.

**Comment by joepavitt** [comment]
How about _"FlowFuse - The power of Integration at Industrial scale"_?

**Comment by Yndira-E** [comment]
> How about "FlowFuse - The power of Integration at Industrial scale"?

I like how it reads/sounds, though I’d consider skipping the word "FlowFuse."
I also appreciate that it’s shorter, and I agree it’s catchier.

On the other hand, I wonder if "integration" is the right word to describe everything the Node-RED + FlowFuse combo enables. Do we think this aligns with the main goal of our ICP? @zackwasli @MichaelBDavis

[This document](https://docs.google.com/document/d/1LllLXbeJRjPTMyqhhA47LW7xwS__7HrFfVXqeE64Fw0/edit?usp=sharing) from the summer leans toward focusing on data instead, which reflects the current state. Meanwhile, the Node-RED homepage describes it as _"Low-code programming for event-driven applications"_—so perhaps "automation" could be another option?

**Comment by gstout52** [comment]
Proposal:

Tagline: The Power of Integration at Industrial Scale
Comment: This captures the essential problem that FlowFuse solves, including data transformation/acquisition/visualization. (See [ICP notes from October](https://docs.google.com/document/d/1F4fFUtW3qqFmmwX4cz9JOolNmO1Ozt60dOgMcEsyZfg/edit?tab=t.0), and the doc Yndira linked to.)

Subtitle: "Supercharge your industrial operations with tools built for seamless collaboration, effortless deployment, and scalable solutions. FlowFuse simplifies development, accelerates delivery, and ensures reliability—all in one platform"
Comment: This is a shortened version of what I proposed previously, replacing "manufacturing" with "industrial", and is at 230 characters to the current 166 characters.

I think we can be thoughtful about our approach to the homepage as a whole, but should approach the entire project iteratively, so I'm glad to be working together on this first part.
@Hasmin-AC Thoughts about the revised subtitle?

**Comment by ZJvandeWeg** [comment]
@gstout52 Can you update the PR to have that text and it's easier to merge?

**Comment by gstout52** [comment]
The PR has been updated. I'll create a PostHog chart and link to it in a comment on this PR, and we can evaluate performance before/after.

**Comment by gstout52** [comment]
November 22 is when the new copy went live.

Charts:

Homepage view > CTA Learn More: https://eu.posthog.com/project/2209/insights/0usf57Si

Homepage view > CTA Contact Us: https://eu.posthog.com/project/2209/insights/Bcp6ldH8

Homepage view > Signed Up for Trial: https://eu.posthog.com/project/2209/insights/ZjUC9xsg

We can also keep an eye on the full funnel on the main dashboard: https://eu.posthog.com/project/2209

**Comment by gstout52** [comment]
Update. As of now, there isn't a significant change in performance for signups or sales contacts, both of which are roughly steady from since before the change on November 22.

Surprisingly, the main change has been in _increase_ in page conversion to Learn More, which had been converting from pageview > learn more at about 0-1% and is now at 3-4.5%. 

To see this, click into the charts in the previous comment, click edit, and change conversion to 1 day.

We'll continue to monitor this change.

**Comment by Yndira-E** [comment]
Hey Greg,

I think the change you're seeing might be due to the fact that, prior to [this change](https://github.com/FlowFuse/website/pull/2816/files), the `Learn More` button in the hero section of the homepage wasn’t capturing clicks for that CTA.

The recorded data you had was coming from the `Learn More` button on the [Dedicated Hosting pricing page](https://flowfuse.com/pricing/?hosting=dedicated).

To see data specific to the button in the hero section of the homepage, you'll need to add a filter for that particular element (position equals hero).

I’ve created a few reports to measure the performance of the buttons that aren’t tied to the previous CTA tracking. You can find them in [this dashboard](https://eu.posthog.com/project/2209/dashboard/37078).

It’s only been a week since the button changes, but here’s what the data shows so far:
- The `Learn More` CTA click-through rate (CTR) has decreased from **2.5%** to **1.9%**.  
- The main CTA (previously `Learn More`, now `Try It Out`) has increased from **2.5%** to **5.5%** **more than doubling its previous performance.**
    - From clicking on that button to actually signing up, the numbers are better than they were between June and September of this year (from 20% to 37%).  
    - However, from your reports, I can see that sign-ups haven’t spiked significantly since the button changes. We've recently updated the copy on the sign-up page, so perhaps that will help improve the numbers in the coming weeks.  

Let me know if you’d like to dig into the reports together!

**Pull request merged**
