### PR TITLE
Blog : Using FlowFuse Project Nodes for Faster and More Efficient Com…

### PR DESCRIPTION
**Pull request by sumitshinde-84**
…munication

## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Review by Steve-Mcl — APPROVED** [review]
This is a good clean well written article.

If I had to say one thing it would be not calling out when/why to use broadcast vs direct.  That could be a follow up article (a part 2, deeper dive) that refers back to this article as reference.

I will approve, you can decide to update or follow up.

**Comment by Steve-Mcl** [comment]
PS, @sumitshinde-84 If something is ready for review, please mark it as read for review.

**Comment by Steve-Mcl** [comment]
Sorry, forgot to add, the date probably needs updating (it is currently marked as Sept 13th)

**Review by Steve-Mcl — CHANGES_REQUESTED** [review]
You seem to have an image added to the `09/images` directory

**Comment by sumitshinde-84** [comment]
> You seem to have an image added to the `09/images` directory

Removed Now !

**Review by Steve-Mcl — APPROVED** [review]
all good.

Will probably need the date updating one last time before publish.

**Pull request merged**
