### PR TITLE
pricing: Publish current enterprise pricing

### PR DESCRIPTION
**Pull request by ZJvandeWeg**
## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Review by zackwasli — APPROVED** [review]
Approve the overall change, not sure what errors it is throwing though. How can you see the preview of what the suggested changes will look like again?

**Comment by Yndira-FlowForge** [comment]
@zackwasli 

> How can you see the preview of what the suggested changes will look like again?

Since some checks didn't pass, it doesn't create the preview... You could see it if you had it on local.

**Review by Yndira-FlowForge — COMMENTED** [review]
I saw it on local and it looks good. But netlify is not building it, checks are not passing.

**Comment by Pezmc** [comment]
Netlify appears to now be using node version 20, but the plugin `@netlify/plugin-lighthouse` says it does not run above version 19.

We'll either need to:
 - Configure netlify to use an older version of node
 - Upgrade plugin-lighthouse
 
 The later is going to be fastest, I'll just do that on this PR

**Review by Yndira-FlowForge — APPROVED** [review]

**Pull request merged**
