### PR TITLE
New article for running device-agent as windows service

### PR DESCRIPTION
**Pull request by Steve-Mcl**
## Description

A blog post for describing how to setup the device agent as a windows service using NSSM

### TODO: 
- [x] Proof read & test drive on a different computer
- [x] Request a graphic for the article
  - [x] place in code
- [x] Update the image and release date before publishing
- [x] Add a [link ](https://support.microsoft.com/en-us/windows/create-a-local-user-or-administrator-account-in-windows-20de74e0-ac7f-3502-a866-32915af2a34d#:~:text=Select%20Start%20%3E%20Settings%20%3E%20Accounts%20and,other%20user%2C%20select%20Add%20account.)to creating a User in Windows
- [x] add a link to upgarde your flowfuse device agent
- [x] add screenshot of ```nssm edit flowfuse-device-agent```
- [x] Troubleshooting steps?
- [x] If you have to create a new user restart computer? at minimum restart CMD prompt.
- [x] Add runas /user:winserv cmd

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowforge/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [x] Documentation has been updated

### CODE REVIEW

**Comment by robmarcer** [comment]
I've reviewed the text and made a few small changes which are now in the PR.

Looks like the header image is missing @Steve-Mcl.

**Comment by Steve-Mcl** [comment]
> Looks like the header image is missing @Steve-Mcl.

Indeed. It's listed in the TODOs in the OP Rob. I've handed this over @gdziuba  for verification and finishing touches.

**Comment by gdziuba** [comment]
@Steve-Mcl Do you need me to make an issue for art?  I didn't see one?

**Comment by gdziuba** [comment]
I will run through this tomorrow and verify everything works.  Thanks for the patience.

**Comment by gdziuba** [comment]
@Yndira-FlowForge Do you know if you have an issue for this artwork yet?  I will add it tomorrow if you don't.  Thanks.

**Comment by Steve-Mcl** [comment]
> @Yndira-FlowForge Do you know if you have an issue for this artwork yet? I will add it tomorrow if you don't. Thanks.

Grey, there is not (the TODO list in the OP is up to date)

**Comment by gdziuba** [comment]
Ran into an error.  @robmarcer Maybe we can work on it 8 am ish local time for you this morning.  

```C:\Windows\System32>sc start flowfuse-device-agent

SERVICE_NAME: flowfuse-device-agent
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 2  START_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x7d0
        PID                : 33824
        FLAGS              :

C:\Windows\System32>sc query flowfuse-device-agent

SERVICE_NAME: flowfuse-device-agent
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 1066  (0x42a)
        SERVICE_EXIT_CODE  : 3  (0x3)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0```

**Comment by Steve-Mcl** [comment]
@gdziuba it is possible one of the steps were not followed correctly.  My guess is one of the commands where you are supposed to change "user" to the _real_user_on_your_computer_ (my money is on the icacls command didn't set permissions for the user account)

I would try again from scratch 🤞

**Review by gdziuba — APPROVED** [review]

**Pull request merged**
