### PR TITLE
Content - Product Strategy Updates

### PR DESCRIPTION
**Pull request by joepavitt**
## Description

Details the recent updates to https://flowfuse.com/handbook/product/strategy/ in a more consumer-friendly format, and gives us a vehicle by which to talk about product features/pillars on socials.

## Related Issue(s)

Art Request: https://github.com/FlowFuse/website/issues/2038

### CODE REVIEW

**Comment by joepavitt** [comment]
Build failing due to missing image

**Comment by joepavitt** [comment]
Bit late in the day on a Friday to publish this, but it's now all good to go. Feel free to review/approve/merge on Monday whilst I'm out. It'll be nice to see it go out

**Comment by joepavitt** [comment]
Any supporting socials we do @Yndira-E can we emphasise the "Build", "Manage", "Deploy" phrasing with the article, maybe an emoji to support each too - I want to try and reinforce this messaging as we're doing product updates in the future too

**Comment by Yndira-E** [comment]
For sure, @joepavitt!

**Review by robmarcer — APPROVED** [review]

**Review by knolleary — APPROVED** [review]

**Pull request merged**
