### PR TITLE
Upload teal pictograms

### PR DESCRIPTION
**Pull request by Yndira-FlowForge**
## Description

While changing the website colours I removed the teal pictograms because they're no longer needed in the web, but some are in the platform. This PR brings them back.

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by knolleary** [comment]
I don't think we strictly need all of them, but can review exactly which ones are used by the app separately.

**Review by knolleary — APPROVED** [review]
The 'create account' view of the app uses 'time.png' and 'no_credit_card.png' from this collection.

**Comment by Yndira-FlowForge** [comment]
Ok, I thought it would take too long, if you can provide a list, I'll upload only the ones we need.

**Comment by knolleary** [comment]
Lets merge all to get things fixed and then we can be more selective afterwards.

**Pull request merged**
