### PR TITLE
update the trailing slash logic

### PR DESCRIPTION
**Pull request by sumitshinde-84**
## Checklist

 - [ ] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [ ] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by knolleary** [comment]
Why do we need to rewrite the sign up url? The canonical version is `https://app.flowfuse.com/account/create` without the trailing `/`.

**Comment by sumitshinde-84** [comment]
I've just checked that our sign-up page is not indexed—neither `https://app.flowfuse.com/account/create` nor `https://app.flowfuse.com/account/create/`.

**Comment by sumitshinde-84** [comment]
@joepavitt, that's why I think our sign-up page doesn't have any views ( you mentioned that in the channel).

**Comment by joepavitt** [comment]
> that's why I think our sign-up page doesn't have any clicks( you mentioned that in the channel).

That's a PostHog problem - we're getting the traffic/views, PostHog just isn't recording it accurately.

**Comment by sumitshinde-84** [comment]
Okay! For now, I am removing the logic to include the / for the sign-up page.

**Review by knolleary — APPROVED** [review]

**Pull request merged**
