### PR TITLE
Home page iteration

### PR DESCRIPTION
**Pull request by Yndira-E**
## Description

- [x] 1. Update description in the hero section
- [x] 2. In the second section, the "See how FlowFuse powers industries", replace the content with actual industries:
    - Manufacturing
    - Agriculture
    - Building management system
- [x] 3. Replace benefits with values
- [x] 4. Replace get started > learn more with on premises (like in `/features`)
- [x] 5. Replace Nick's video with animation

## Related Issue(s)

[#1960](https://github.com/FlowFuse/website/issues/1960)

## Checklist

 - [x] I have read the [contribution guidelines](https://github.com/FlowFuse/flowfuse/blob/main/CONTRIBUTING.md)
 - [x] I have considered the performance impact of these changes
 - [ ] Suitable unit/system level tests have been added and they pass
 - [ ] Documentation has been updated

### CODE REVIEW

**Comment by Yndira-E** [comment]
@ZJvandeWeg I've added the copy for the values section based on what Hasmin provided. If we stick with three values, updates should be easy.

**Comment by Yndira-E** [comment]
And I'm keeping it as a draft until we have the updated copy for that section

**Comment by ZJvandeWeg** [comment]
@Yndira-E Can we merge and iterate? I don't understand why you'd block progress

**Comment by Yndira-E** [comment]
I thought we would have the copy for the values updated yesterday, I didn't mean to block progress. Everything else is ready and I wasn't sure if the values were good enough to go live as they are now. Feel free to review/merge.

**Pull request merged**
